extends = "../../../config/models.toml"

[models.detect-fast]
path = "tools/model-tools/artifacts/yolo26-fp16/yolo26m-fp16-192.onnx"
imgsz = 192

[models.face-yolo]
path = "tools/model-tools/artifacts/yoloface-fp16/yolov12m-face-fp16-192.onnx"
imgsz = 192

[models.pose-standard]
path = "tools/model-tools/artifacts/yolo26-fp16/yolo26m-pose-fp16-192.onnx"
imgsz = 192

[models.seg-standard]
path = "tools/model-tools/artifacts/yolo26-fp16/yolo26m-seg-fp16-192.onnx"
imgsz = 192
